version: '3'

services:
  backend_api:
    build:
      context: .
      dockerfile: ./docker/local/api/Dockerfile
    image: image_pi_backend_app
    container_name: container_pi_backend_app
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - .:/app
    env_file:
      - .env

  # db:
